version: '0.1'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-127.0.0.1}:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3    # 오프셋 저장에 사용될 복제 수
      KAFKA_LOG_RETENTION_HOURS: 48                # 로그 보관 시간
      KAFKA_LOG_SEGMENT_BYTES: 1073741824          # 로그 세그먼트 크기 (기본값: 1GB)
      KAFKA_DELETE_TOPIC_ENABLE: "true"            # 토픽 삭제 활성화
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"     # 자동 토픽 생성 비활성화
      #KAFKA_MIN_INSYNC_REPLICAS: 2                 # 최소 동기화된 복제본 수
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 4
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: true   # 리더 리밸런싱 활성화
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: 20   # 리더 불균형 비율 설정
      KAFKA_IMBALACE_CHECK_INTERVAL_SECONDS: 10
      KAFKA_PRODUCER_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: 3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
